/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Answer { 'isCorrect' : boolean, 'questionId' : string }
export type Difficulty = { 'mastery' : null } |
  { 'intermediate' : null } |
  { 'elementary' : null } |
  { 'beginner' : null } |
  { 'advanced' : null } |
  { 'expert' : null };
export interface Lesson {
  'id' : string,
  'title' : string,
  'question' : string,
  'subject' : Subject,
  'xpReward' : bigint,
  'difficulty' : Difficulty,
  'correctAnswer' : string,
  'coinReward' : bigint,
  'worldId' : string,
  'isBossBattle' : boolean,
  'optionA' : string,
  'optionB' : string,
  'optionC' : string,
  'optionD' : string,
}
export interface LessonProgressRecord {
  'id' : string,
  'userId' : string,
  'completed' : boolean,
  'worldName' : string,
  'dateCompleted' : bigint,
  'score' : bigint,
  'lessonName' : string,
  'xpEarned' : bigint,
}
export interface MultiplayerSession {
  'id' : string,
  'status' : SessionStatus,
  'opponentId' : [] | [string],
  'subject' : Subject,
  'winnerId' : [] | [string],
  'hostId' : string,
}
export interface Purchase {
  'id' : string,
  'itemId' : string,
  'purchaseDate' : bigint,
  'cost' : bigint,
  'userId' : string,
  'itemType' : PurchaseType,
}
export type PurchaseType = { 'hintPack' : null } |
  { 'worldSkin' : null } |
  { 'avatarCostume' : null };
export interface Quest {
  'id' : string,
  'title' : string,
  'expiresAt' : bigint,
  'xpReward' : bigint,
  'description' : string,
  'coinReward' : bigint,
  'isDaily' : boolean,
}
export type SessionStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface SkillNode {
  'id' : string,
  'subject' : Subject,
  'requiredLevel' : bigint,
  'name' : string,
  'prerequisiteIds' : Array<string>,
}
export interface StreakRecord {
  'userId' : string,
  'longestStreak' : bigint,
  'lastStreakDate' : bigint,
  'currentStreak' : bigint,
}
export type Subject = { 'math' : null } |
  { 'english' : null };
export interface TutorRecommendation {
  'recommendedLesson' : string,
  'hint' : string,
  'difficultyAdjustment' : Difficulty,
}
export interface User {
  'id' : string,
  'xp' : bigint,
  'age' : bigint,
  'lastLoginDate' : bigint,
  'principal' : Principal,
  'username' : string,
  'gems' : bigint,
  'coins' : bigint,
  'streakDays' : bigint,
  'level' : bigint,
  'avatarId' : string,
  'currentWorldId' : string,
  'subjectProgress' : Array<[Subject, bigint]>,
}
export interface UserProfile {
  'age' : bigint,
  'username' : string,
  'avatarId' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSkillNode {
  'userId' : string,
  'unlocked' : boolean,
  'skillNodeId' : string,
}
export interface World {
  'id' : string,
  'subject' : Subject,
  'requiredLevel' : bigint,
  'order' : bigint,
  'difficulty' : Difficulty,
  'name' : string,
  'unlockXp' : bigint,
  'description' : string,
  'isUnlocked' : boolean,
  'bossDefeated' : boolean,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimStreakReward' : ActorMethod<[string], string>,
  'completeQuest' : ActorMethod<[string, string], undefined>,
  'createChallenge' : ActorMethod<[string, Subject], string>,
  'createLesson' : ActorMethod<[Lesson], string>,
  'createQuest' : ActorMethod<[Quest], string>,
  'createSkillNode' : ActorMethod<[SkillNode], string>,
  'createUser' : ActorMethod<[string, bigint, string], string>,
  'deleteLesson' : ActorMethod<[string], undefined>,
  'deleteQuest' : ActorMethod<[string], undefined>,
  'deleteSkillNode' : ActorMethod<[string], undefined>,
  'deleteUser' : ActorMethod<[string], undefined>,
  'getAvailableWorlds' : ActorMethod<[string], Array<World>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyQuests' : ActorMethod<[string], Array<Quest>>,
  'getLesson' : ActorMethod<[string], [] | [Lesson]>,
  'getLessonsByWorld' : ActorMethod<[string], Array<Lesson>>,
  'getMultiplayerSession' : ActorMethod<[string], [] | [MultiplayerSession]>,
  'getQuest' : ActorMethod<[string], [] | [Quest]>,
  'getSkillNode' : ActorMethod<[string], [] | [SkillNode]>,
  'getSkillTree' : ActorMethod<[Subject], Array<SkillNode>>,
  'getStreakStatus' : ActorMethod<[string], [] | [StreakRecord]>,
  'getTutorRecommendation' : ActorMethod<
    [string, Subject],
    TutorRecommendation
  >,
  'getUser' : ActorMethod<[string], [] | [User]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProgress' : ActorMethod<[string], Array<LessonProgressRecord>>,
  'getUserPurchases' : ActorMethod<[string], Array<Purchase>>,
  'getUserSkillNodes' : ActorMethod<[string], Array<UserSkillNode>>,
  'getWorld' : ActorMethod<[string], [] | [World]>,
  'getWorldLessons' : ActorMethod<[string], Array<Lesson>>,
  'getWorldProgress' : ActorMethod<
    [string, string],
    Array<LessonProgressRecord>
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinChallenge' : ActorMethod<[string, string], undefined>,
  'listLessons' : ActorMethod<[], Array<Lesson>>,
  'listWorlds' : ActorMethod<[], Array<World>>,
  'purchaseItem' : ActorMethod<[string, PurchaseType, string], string>,
  'recordLessonResult' : ActorMethod<[string, string, bigint], undefined>,
  'recordLogin' : ActorMethod<[string], undefined>,
  'recordProgress' : ActorMethod<
    [string, string, string, bigint, bigint],
    string
  >,
  'resolveSession' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitAnswers' : ActorMethod<[string, string, Array<Answer>], undefined>,
  'unlockSkillNode' : ActorMethod<[string, string], undefined>,
  'updateLesson' : ActorMethod<[Lesson], undefined>,
  'updateQuest' : ActorMethod<[Quest], undefined>,
  'updateSkillNode' : ActorMethod<[SkillNode], undefined>,
  'updateUser' : ActorMethod<[User], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];