/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserSkillNode {
    userId: string;
    unlocked: boolean;
    skillNodeId: string;
}
export interface StreakRecord {
    userId: string;
    longestStreak: bigint;
    lastStreakDate: bigint;
    currentStreak: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface User {
    id: string;
    xp: bigint;
    age: bigint;
    lastLoginDate: bigint;
    principal: Principal;
    username: string;
    gems: bigint;
    coins: bigint;
    streakDays: bigint;
    level: bigint;
    avatarId: string;
    currentWorldId: string;
    subjectProgress: Array<[Subject, bigint]>;
}
export interface SkillNode {
    id: string;
    subject: Subject;
    requiredLevel: bigint;
    name: string;
    prerequisiteIds: Array<string>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface TutorRecommendation {
    recommendedLesson: string;
    hint: string;
    difficultyAdjustment: Difficulty;
}
export interface MultiplayerSession {
    id: string;
    status: SessionStatus;
    opponentId?: string;
    subject: Subject;
    winnerId?: string;
    hostId: string;
}
export interface Lesson {
    id: string;
    title: string;
    subject: Subject;
    xpReward: bigint;
    difficulty: Difficulty;
    coinReward: bigint;
    worldId: string;
    isBossBattle: boolean;
}
export interface Quest {
    id: string;
    title: string;
    expiresAt: bigint;
    xpReward: bigint;
    description: string;
    coinReward: bigint;
    isDaily: boolean;
}
export interface Answer {
    isCorrect: boolean;
    questionId: string;
}
export interface Purchase {
    id: string;
    itemId: string;
    purchaseDate: bigint;
    cost: bigint;
    userId: string;
    itemType: PurchaseType;
}
export interface World {
    id: string;
    subject: Subject;
    requiredLevel: bigint;
    difficulty: Difficulty;
    name: string;
    isUnlocked: boolean;
    bossDefeated: boolean;
}
export interface UserProfile {
    age: bigint;
    username: string;
    avatarId: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum Difficulty {
    mastery = "mastery",
    intermediate = "intermediate",
    elementary = "elementary",
    beginner = "beginner",
    advanced = "advanced",
    expert = "expert"
}
export enum PurchaseType {
    hintPack = "hintPack",
    worldSkin = "worldSkin",
    avatarCostume = "avatarCostume"
}
export enum SessionStatus {
    pending = "pending",
    completed = "completed",
    inProgress = "inProgress"
}
export enum Subject {
    math = "math",
    english = "english"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Claim streak reward for a user. Only the owning user may claim their reward.
     */
    claimStreakReward(userId: string): Promise<string>;
    /**
     * / Complete a quest for a user. Only the owning user may complete their quests.
     */
    completeQuest(userId: string, questId: string): Promise<void>;
    /**
     * / Create a multiplayer challenge. Only authenticated users may create challenges.
     */
    createChallenge(hostId: string, subject: Subject): Promise<string>;
    /**
     * / Create a lesson. Admin only.
     */
    createLesson(lesson: Lesson): Promise<string>;
    /**
     * / Create a quest. Admin only.
     */
    createQuest(quest: Quest): Promise<string>;
    /**
     * / Create a skill node. Admin only.
     */
    createSkillNode(skillNode: SkillNode): Promise<string>;
    /**
     * / Create a new game user record for the caller.
     * / Requires the caller to be an authenticated user (not a guest).
     */
    createUser(username: string, age: bigint, avatarId: string): Promise<string>;
    /**
     * / Create a world. Admin only.
     */
    createWorld(world: World): Promise<string>;
    /**
     * / Delete a lesson. Admin only.
     */
    deleteLesson(id: string): Promise<void>;
    /**
     * / Delete a quest. Admin only.
     */
    deleteQuest(id: string): Promise<void>;
    /**
     * / Delete a skill node. Admin only.
     */
    deleteSkillNode(id: string): Promise<void>;
    /**
     * / Delete a user record. Only the owning principal or an admin may delete it.
     */
    deleteUser(id: string): Promise<void>;
    /**
     * / Delete a world. Admin only.
     */
    deleteWorld(id: string): Promise<void>;
    /**
     * / Get the caller's own profile.
     */
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Get daily quests for a user. Only the owning user or an admin may call this.
     */
    getDailyQuests(userId: string): Promise<Array<Quest>>;
    /**
     * / Read a lesson. Any authenticated user may read lesson data.
     */
    getLesson(id: string): Promise<Lesson | null>;
    /**
     * / List lessons for a specific world. Any authenticated user may call this.
     */
    getLessonsByWorld(worldId: string): Promise<Array<Lesson>>;
    /**
     * / Get a multiplayer session. Participants or admins only.
     */
    getMultiplayerSession(sessionId: string): Promise<MultiplayerSession | null>;
    /**
     * / Read a quest. Any authenticated user may read quest data.
     */
    getQuest(id: string): Promise<Quest | null>;
    /**
     * / Read a skill node. Any authenticated user may read skill node data.
     */
    getSkillNode(id: string): Promise<SkillNode | null>;
    /**
     * / Get all skill nodes for a subject. Any authenticated user may call this.
     */
    getSkillTree(subject: Subject): Promise<Array<SkillNode>>;
    /**
     * / Get streak status for a user. Only the owning user or an admin may call this.
     */
    getStreakStatus(userId: string): Promise<StreakRecord | null>;
    /**
     * / Get a tutor recommendation for a user. Only the owning user or an admin may call this.
     */
    getTutorRecommendation(userId: string, subject: Subject): Promise<TutorRecommendation>;
    /**
     * / Retrieve a user record. Only the owning principal or an admin may read it.
     */
    getUser(id: string): Promise<User | null>;
    /**
     * / Fetch another user's profile. Callers may only view their own profile
     * / unless they are an admin.
     */
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    /**
     * / Get all purchases for a user. Only the owning user or an admin may call this.
     */
    getUserPurchases(userId: string): Promise<Array<Purchase>>;
    /**
     * / Get all skill nodes unlocked by a user. Only the owning user or an admin may call this.
     */
    getUserSkillNodes(userId: string): Promise<Array<UserSkillNode>>;
    /**
     * / Read a world. Any authenticated user may read world data.
     */
    getWorld(id: string): Promise<World | null>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / Join a multiplayer challenge. Only authenticated users may join challenges.
     */
    joinChallenge(sessionId: string, opponentId: string): Promise<void>;
    /**
     * / List all lessons. Any authenticated user may list lessons.
     */
    listLessons(): Promise<Array<Lesson>>;
    /**
     * / List all worlds. Any authenticated user may list worlds.
     */
    listWorlds(): Promise<Array<World>>;
    /**
     * / Purchase an item from the shop. Only the owning user may make purchases.
     */
    purchaseItem(userId: string, itemType: PurchaseType, itemId: string): Promise<string>;
    /**
     * / Record a lesson result for a user. Only the owning user may record their results.
     */
    recordLessonResult(userId: string, lessonId: string, score: bigint): Promise<void>;
    /**
     * / Record a daily login for a user. Only the owning user may record their login.
     */
    recordLogin(userId: string): Promise<void>;
    /**
     * / Resolve a multiplayer session. Only authenticated users (participants) or admins may resolve.
     */
    resolveSession(sessionId: string): Promise<void>;
    /**
     * / Save / update the caller's own profile.
     */
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    /**
     * / Submit answers for a multiplayer session. Only the participating user may submit.
     */
    submitAnswers(sessionId: string, userId: string, answers: Array<Answer>): Promise<void>;
    /**
     * / Unlock a skill node for a user. Only the owning user may unlock their nodes.
     */
    unlockSkillNode(userId: string, nodeId: string): Promise<void>;
    /**
     * / Update a lesson. Admin only.
     */
    updateLesson(lesson: Lesson): Promise<void>;
    /**
     * / Update a quest. Admin only.
     */
    updateQuest(quest: Quest): Promise<void>;
    /**
     * / Update a skill node. Admin only.
     */
    updateSkillNode(skillNode: SkillNode): Promise<void>;
    /**
     * / Update a user record. Only the owning principal or an admin may update it.
     */
    updateUser(user: User): Promise<void>;
    /**
     * / Update a world. Admin only.
     */
    updateWorld(world: World): Promise<void>;
}
import type { Difficulty as _Difficulty, Lesson as _Lesson, MultiplayerSession as _MultiplayerSession, Purchase as _Purchase, PurchaseType as _PurchaseType, Quest as _Quest, SessionStatus as _SessionStatus, SkillNode as _SkillNode, StreakRecord as _StreakRecord, Subject as _Subject, TutorRecommendation as _TutorRecommendation, User as _User, UserProfile as _UserProfile, UserRole as _UserRole, World as _World, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async claimStreakReward(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.claimStreakReward(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimStreakReward(arg0);
            return result;
        }
    }
    async completeQuest(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeQuest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeQuest(arg0, arg1);
            return result;
        }
    }
    async createChallenge(arg0: string, arg1: Subject): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createChallenge(arg0, to_candid_Subject_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChallenge(arg0, to_candid_Subject_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createLesson(arg0: Lesson): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createLesson(to_candid_Lesson_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLesson(to_candid_Lesson_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createQuest(arg0: Quest): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createQuest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createQuest(arg0);
            return result;
        }
    }
    async createSkillNode(arg0: SkillNode): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createSkillNode(to_candid_SkillNode_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSkillNode(to_candid_SkillNode_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createUser(arg0: string, arg1: bigint, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, arg1, arg2);
            return result;
        }
    }
    async createWorld(arg0: World): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createWorld(to_candid_World_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWorld(to_candid_World_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteLesson(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLesson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLesson(arg0);
            return result;
        }
    }
    async deleteQuest(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteQuest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteQuest(arg0);
            return result;
        }
    }
    async deleteSkillNode(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSkillNode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSkillNode(arg0);
            return result;
        }
    }
    async deleteUser(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return result;
        }
    }
    async deleteWorld(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWorld(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWorld(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyQuests(arg0: string): Promise<Array<Quest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyQuests(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyQuests(arg0);
            return result;
        }
    }
    async getLesson(arg0: string): Promise<Lesson | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLesson(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLesson(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLessonsByWorld(arg0: string): Promise<Array<Lesson>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLessonsByWorld(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLessonsByWorld(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMultiplayerSession(arg0: string): Promise<MultiplayerSession | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMultiplayerSession(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMultiplayerSession(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuest(arg0: string): Promise<Quest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuest(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuest(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSkillNode(arg0: string): Promise<SkillNode | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSkillNode(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSkillNode(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSkillTree(arg0: Subject): Promise<Array<SkillNode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSkillTree(to_candid_Subject_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSkillTree(to_candid_Subject_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStreakStatus(arg0: string): Promise<StreakRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStreakStatus(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStreakStatus(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTutorRecommendation(arg0: string, arg1: Subject): Promise<TutorRecommendation> {
        if (this.processError) {
            try {
                const result = await this.actor.getTutorRecommendation(arg0, to_candid_Subject_n10(this._uploadFile, this._downloadFile, arg1));
                return from_candid_TutorRecommendation_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTutorRecommendation(arg0, to_candid_Subject_n10(this._uploadFile, this._downloadFile, arg1));
            return from_candid_TutorRecommendation_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUser(arg0: string): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserPurchases(arg0: string): Promise<Array<Purchase>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPurchases(arg0);
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPurchases(arg0);
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserSkillNodes(arg0: string): Promise<Array<UserSkillNode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSkillNodes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSkillNodes(arg0);
            return result;
        }
    }
    async getWorld(arg0: string): Promise<World | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorld(arg0);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorld(arg0);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async joinChallenge(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinChallenge(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinChallenge(arg0, arg1);
            return result;
        }
    }
    async listLessons(): Promise<Array<Lesson>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLessons();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLessons();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async listWorlds(): Promise<Array<World>> {
        if (this.processError) {
            try {
                const result = await this.actor.listWorlds();
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listWorlds();
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async purchaseItem(arg0: string, arg1: PurchaseType, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.purchaseItem(arg0, to_candid_PurchaseType_n59(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchaseItem(arg0, to_candid_PurchaseType_n59(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async recordLessonResult(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordLessonResult(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordLessonResult(arg0, arg1, arg2);
            return result;
        }
    }
    async recordLogin(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordLogin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordLogin(arg0);
            return result;
        }
    }
    async resolveSession(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resolveSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resolveSession(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitAnswers(arg0: string, arg1: string, arg2: Array<Answer>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAnswers(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAnswers(arg0, arg1, arg2);
            return result;
        }
    }
    async unlockSkillNode(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlockSkillNode(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlockSkillNode(arg0, arg1);
            return result;
        }
    }
    async updateLesson(arg0: Lesson): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLesson(to_candid_Lesson_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLesson(to_candid_Lesson_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateQuest(arg0: Quest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateQuest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateQuest(arg0);
            return result;
        }
    }
    async updateSkillNode(arg0: SkillNode): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSkillNode(to_candid_SkillNode_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSkillNode(to_candid_SkillNode_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateUser(arg0: User): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(to_candid_User_n61(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(to_candid_User_n61(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateWorld(arg0: World): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorld(to_candid_World_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorld(to_candid_World_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Difficulty_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Difficulty): Difficulty {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Lesson_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Lesson): Lesson {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_MultiplayerSession_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MultiplayerSession): MultiplayerSession {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_PurchaseType_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PurchaseType): PurchaseType {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_Purchase_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Purchase): Purchase {
    return from_candid_record_n52(_uploadFile, _downloadFile, value);
}
function from_candid_SessionStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionStatus): SessionStatus {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_SkillNode_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SkillNode): SkillNode {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Subject_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Subject): Subject {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_TutorRecommendation_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TutorRecommendation): TutorRecommendation {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_User_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_World_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _World): World {
    return from_candid_record_n57(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Lesson]): Lesson | null {
    return value.length === 0 ? null : from_candid_Lesson_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MultiplayerSession]): MultiplayerSession | null {
    return value.length === 0 ? null : from_candid_MultiplayerSession_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Quest]): Quest | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SkillNode]): SkillNode | null {
    return value.length === 0 ? null : from_candid_SkillNode_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StreakRecord]): StreakRecord | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n46(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_World]): World | null {
    return value.length === 0 ? null : from_candid_World_n56(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    subject: _Subject;
    xpReward: bigint;
    difficulty: _Difficulty;
    coinReward: bigint;
    worldId: string;
    isBossBattle: boolean;
}): {
    id: string;
    title: string;
    subject: Subject;
    xpReward: bigint;
    difficulty: Difficulty;
    coinReward: bigint;
    worldId: string;
    isBossBattle: boolean;
} {
    return {
        id: value.id,
        title: value.title,
        subject: from_candid_Subject_n26(_uploadFile, _downloadFile, value.subject),
        xpReward: value.xpReward,
        difficulty: from_candid_Difficulty_n28(_uploadFile, _downloadFile, value.difficulty),
        coinReward: value.coinReward,
        worldId: value.worldId,
        isBossBattle: value.isBossBattle
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _SessionStatus;
    opponentId: [] | [string];
    subject: _Subject;
    winnerId: [] | [string];
    hostId: string;
}): {
    id: string;
    status: SessionStatus;
    opponentId?: string;
    subject: Subject;
    winnerId?: string;
    hostId: string;
} {
    return {
        id: value.id,
        status: from_candid_SessionStatus_n34(_uploadFile, _downloadFile, value.status),
        opponentId: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.opponentId)),
        subject: from_candid_Subject_n26(_uploadFile, _downloadFile, value.subject),
        winnerId: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.winnerId)),
        hostId: value.hostId
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    subject: _Subject;
    requiredLevel: bigint;
    name: string;
    prerequisiteIds: Array<string>;
}): {
    id: string;
    subject: Subject;
    requiredLevel: bigint;
    name: string;
    prerequisiteIds: Array<string>;
} {
    return {
        id: value.id,
        subject: from_candid_Subject_n26(_uploadFile, _downloadFile, value.subject),
        requiredLevel: value.requiredLevel,
        name: value.name,
        prerequisiteIds: value.prerequisiteIds
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    recommendedLesson: string;
    hint: string;
    difficultyAdjustment: _Difficulty;
}): {
    recommendedLesson: string;
    hint: string;
    difficultyAdjustment: Difficulty;
} {
    return {
        recommendedLesson: value.recommendedLesson,
        hint: value.hint,
        difficultyAdjustment: from_candid_Difficulty_n28(_uploadFile, _downloadFile, value.difficultyAdjustment)
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    xp: bigint;
    age: bigint;
    lastLoginDate: bigint;
    principal: Principal;
    username: string;
    gems: bigint;
    coins: bigint;
    streakDays: bigint;
    level: bigint;
    avatarId: string;
    currentWorldId: string;
    subjectProgress: Array<[_Subject, bigint]>;
}): {
    id: string;
    xp: bigint;
    age: bigint;
    lastLoginDate: bigint;
    principal: Principal;
    username: string;
    gems: bigint;
    coins: bigint;
    streakDays: bigint;
    level: bigint;
    avatarId: string;
    currentWorldId: string;
    subjectProgress: Array<[Subject, bigint]>;
} {
    return {
        id: value.id,
        xp: value.xp,
        age: value.age,
        lastLoginDate: value.lastLoginDate,
        principal: value.principal,
        username: value.username,
        gems: value.gems,
        coins: value.coins,
        streakDays: value.streakDays,
        level: value.level,
        avatarId: value.avatarId,
        currentWorldId: value.currentWorldId,
        subjectProgress: from_candid_vec_n48(_uploadFile, _downloadFile, value.subjectProgress)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    itemId: string;
    purchaseDate: bigint;
    cost: bigint;
    userId: string;
    itemType: _PurchaseType;
}): {
    id: string;
    itemId: string;
    purchaseDate: bigint;
    cost: bigint;
    userId: string;
    itemType: PurchaseType;
} {
    return {
        id: value.id,
        itemId: value.itemId,
        purchaseDate: value.purchaseDate,
        cost: value.cost,
        userId: value.userId,
        itemType: from_candid_PurchaseType_n53(_uploadFile, _downloadFile, value.itemType)
    };
}
function from_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    subject: _Subject;
    requiredLevel: bigint;
    difficulty: _Difficulty;
    name: string;
    isUnlocked: boolean;
    bossDefeated: boolean;
}): {
    id: string;
    subject: Subject;
    requiredLevel: bigint;
    difficulty: Difficulty;
    name: string;
    isUnlocked: boolean;
    bossDefeated: boolean;
} {
    return {
        id: value.id,
        subject: from_candid_Subject_n26(_uploadFile, _downloadFile, value.subject),
        requiredLevel: value.requiredLevel,
        difficulty: from_candid_Difficulty_n28(_uploadFile, _downloadFile, value.difficulty),
        name: value.name,
        isUnlocked: value.isUnlocked,
        bossDefeated: value.bossDefeated
    };
}
function from_candid_tuple_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_Subject, bigint]): [Subject, bigint] {
    return [
        from_candid_Subject_n26(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    math: null;
} | {
    english: null;
}): Subject {
    return "math" in value ? Subject.math : "english" in value ? Subject.english : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mastery: null;
} | {
    intermediate: null;
} | {
    elementary: null;
} | {
    beginner: null;
} | {
    advanced: null;
} | {
    expert: null;
}): Difficulty {
    return "mastery" in value ? Difficulty.mastery : "intermediate" in value ? Difficulty.intermediate : "elementary" in value ? Difficulty.elementary : "beginner" in value ? Difficulty.beginner : "advanced" in value ? Difficulty.advanced : "expert" in value ? Difficulty.expert : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): SessionStatus {
    return "pending" in value ? SessionStatus.pending : "completed" in value ? SessionStatus.completed : "inProgress" in value ? SessionStatus.inProgress : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hintPack: null;
} | {
    worldSkin: null;
} | {
    avatarCostume: null;
}): PurchaseType {
    return "hintPack" in value ? PurchaseType.hintPack : "worldSkin" in value ? PurchaseType.worldSkin : "avatarCostume" in value ? PurchaseType.avatarCostume : value;
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Lesson>): Array<Lesson> {
    return value.map((x)=>from_candid_Lesson_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SkillNode>): Array<SkillNode> {
    return value.map((x)=>from_candid_SkillNode_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_Subject, bigint]>): Array<[Subject, bigint]> {
    return value.map((x)=>from_candid_tuple_n49(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Purchase>): Array<Purchase> {
    return value.map((x)=>from_candid_Purchase_n51(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_World>): Array<World> {
    return value.map((x)=>from_candid_World_n56(_uploadFile, _downloadFile, x));
}
function to_candid_Difficulty_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): _Difficulty {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_Lesson_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Lesson): _Lesson {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_PurchaseType_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PurchaseType): _PurchaseType {
    return to_candid_variant_n60(_uploadFile, _downloadFile, value);
}
function to_candid_SkillNode_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SkillNode): _SkillNode {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_Subject_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Subject): _Subject {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_User_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: User): _User {
    return to_candid_record_n62(_uploadFile, _downloadFile, value);
}
function to_candid_World_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: World): _World {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    subject: Subject;
    xpReward: bigint;
    difficulty: Difficulty;
    coinReward: bigint;
    worldId: string;
    isBossBattle: boolean;
}): {
    id: string;
    title: string;
    subject: _Subject;
    xpReward: bigint;
    difficulty: _Difficulty;
    coinReward: bigint;
    worldId: string;
    isBossBattle: boolean;
} {
    return {
        id: value.id,
        title: value.title,
        subject: to_candid_Subject_n10(_uploadFile, _downloadFile, value.subject),
        xpReward: value.xpReward,
        difficulty: to_candid_Difficulty_n14(_uploadFile, _downloadFile, value.difficulty),
        coinReward: value.coinReward,
        worldId: value.worldId,
        isBossBattle: value.isBossBattle
    };
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    subject: Subject;
    requiredLevel: bigint;
    name: string;
    prerequisiteIds: Array<string>;
}): {
    id: string;
    subject: _Subject;
    requiredLevel: bigint;
    name: string;
    prerequisiteIds: Array<string>;
} {
    return {
        id: value.id,
        subject: to_candid_Subject_n10(_uploadFile, _downloadFile, value.subject),
        requiredLevel: value.requiredLevel,
        name: value.name,
        prerequisiteIds: value.prerequisiteIds
    };
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    subject: Subject;
    requiredLevel: bigint;
    difficulty: Difficulty;
    name: string;
    isUnlocked: boolean;
    bossDefeated: boolean;
}): {
    id: string;
    subject: _Subject;
    requiredLevel: bigint;
    difficulty: _Difficulty;
    name: string;
    isUnlocked: boolean;
    bossDefeated: boolean;
} {
    return {
        id: value.id,
        subject: to_candid_Subject_n10(_uploadFile, _downloadFile, value.subject),
        requiredLevel: value.requiredLevel,
        difficulty: to_candid_Difficulty_n14(_uploadFile, _downloadFile, value.difficulty),
        name: value.name,
        isUnlocked: value.isUnlocked,
        bossDefeated: value.bossDefeated
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    xp: bigint;
    age: bigint;
    lastLoginDate: bigint;
    principal: Principal;
    username: string;
    gems: bigint;
    coins: bigint;
    streakDays: bigint;
    level: bigint;
    avatarId: string;
    currentWorldId: string;
    subjectProgress: Array<[Subject, bigint]>;
}): {
    id: string;
    xp: bigint;
    age: bigint;
    lastLoginDate: bigint;
    principal: Principal;
    username: string;
    gems: bigint;
    coins: bigint;
    streakDays: bigint;
    level: bigint;
    avatarId: string;
    currentWorldId: string;
    subjectProgress: Array<[_Subject, bigint]>;
} {
    return {
        id: value.id,
        xp: value.xp,
        age: value.age,
        lastLoginDate: value.lastLoginDate,
        principal: value.principal,
        username: value.username,
        gems: value.gems,
        coins: value.coins,
        streakDays: value.streakDays,
        level: value.level,
        avatarId: value.avatarId,
        currentWorldId: value.currentWorldId,
        subjectProgress: to_candid_vec_n63(_uploadFile, _downloadFile, value.subjectProgress)
    };
}
function to_candid_tuple_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Subject, bigint]): [_Subject, bigint] {
    return [
        to_candid_Subject_n10(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Subject): {
    math: null;
} | {
    english: null;
} {
    return value == Subject.math ? {
        math: null
    } : value == Subject.english ? {
        english: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): {
    mastery: null;
} | {
    intermediate: null;
} | {
    elementary: null;
} | {
    beginner: null;
} | {
    advanced: null;
} | {
    expert: null;
} {
    return value == Difficulty.mastery ? {
        mastery: null
    } : value == Difficulty.intermediate ? {
        intermediate: null
    } : value == Difficulty.elementary ? {
        elementary: null
    } : value == Difficulty.beginner ? {
        beginner: null
    } : value == Difficulty.advanced ? {
        advanced: null
    } : value == Difficulty.expert ? {
        expert: null
    } : value;
}
function to_candid_variant_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PurchaseType): {
    hintPack: null;
} | {
    worldSkin: null;
} | {
    avatarCostume: null;
} {
    return value == PurchaseType.hintPack ? {
        hintPack: null
    } : value == PurchaseType.worldSkin ? {
        worldSkin: null
    } : value == PurchaseType.avatarCostume ? {
        avatarCostume: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Subject, bigint]>): Array<[_Subject, bigint]> {
    return value.map((x)=>to_candid_tuple_n64(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
