/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Answer { 'isCorrect' : boolean, 'questionId' : string }
export type Difficulty = { 'mastery' : null } |
  { 'intermediate' : null } |
  { 'elementary' : null } |
  { 'beginner' : null } |
  { 'advanced' : null } |
  { 'expert' : null };
export interface Lesson {
  'id' : string,
  'title' : string,
  'subject' : Subject,
  'xpReward' : bigint,
  'difficulty' : Difficulty,
  'coinReward' : bigint,
  'worldId' : string,
  'isBossBattle' : boolean,
}
export interface MultiplayerSession {
  'id' : string,
  'status' : SessionStatus,
  'opponentId' : [] | [string],
  'subject' : Subject,
  'winnerId' : [] | [string],
  'hostId' : string,
}
export interface Purchase {
  'id' : string,
  'itemId' : string,
  'purchaseDate' : bigint,
  'cost' : bigint,
  'userId' : string,
  'itemType' : PurchaseType,
}
export type PurchaseType = { 'hintPack' : null } |
  { 'worldSkin' : null } |
  { 'avatarCostume' : null };
export interface Quest {
  'id' : string,
  'title' : string,
  'expiresAt' : bigint,
  'xpReward' : bigint,
  'description' : string,
  'coinReward' : bigint,
  'isDaily' : boolean,
}
export type SessionStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface SkillNode {
  'id' : string,
  'subject' : Subject,
  'requiredLevel' : bigint,
  'name' : string,
  'prerequisiteIds' : Array<string>,
}
export interface StreakRecord {
  'userId' : string,
  'longestStreak' : bigint,
  'lastStreakDate' : bigint,
  'currentStreak' : bigint,
}
export type Subject = { 'math' : null } |
  { 'english' : null };
export interface TutorRecommendation {
  'recommendedLesson' : string,
  'hint' : string,
  'difficultyAdjustment' : Difficulty,
}
export interface User {
  'id' : string,
  'xp' : bigint,
  'age' : bigint,
  'lastLoginDate' : bigint,
  'principal' : Principal,
  'username' : string,
  'gems' : bigint,
  'coins' : bigint,
  'streakDays' : bigint,
  'level' : bigint,
  'avatarId' : string,
  'currentWorldId' : string,
  'subjectProgress' : Array<[Subject, bigint]>,
}
export interface UserProfile {
  'age' : bigint,
  'username' : string,
  'avatarId' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSkillNode {
  'userId' : string,
  'unlocked' : boolean,
  'skillNodeId' : string,
}
export interface World {
  'id' : string,
  'subject' : Subject,
  'requiredLevel' : bigint,
  'difficulty' : Difficulty,
  'name' : string,
  'isUnlocked' : boolean,
  'bossDefeated' : boolean,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Claim streak reward for a user. Only the owning user may claim their reward.
   */
  'claimStreakReward' : ActorMethod<[string], string>,
  /**
   * / Complete a quest for a user. Only the owning user may complete their quests.
   */
  'completeQuest' : ActorMethod<[string, string], undefined>,
  /**
   * / Create a multiplayer challenge. Only authenticated users may create challenges.
   */
  'createChallenge' : ActorMethod<[string, Subject], string>,
  /**
   * / Create a lesson. Admin only.
   */
  'createLesson' : ActorMethod<[Lesson], string>,
  /**
   * / Create a quest. Admin only.
   */
  'createQuest' : ActorMethod<[Quest], string>,
  /**
   * / Create a skill node. Admin only.
   */
  'createSkillNode' : ActorMethod<[SkillNode], string>,
  /**
   * / Create a new game user record for the caller.
   * / Requires the caller to be an authenticated user (not a guest).
   */
  'createUser' : ActorMethod<[string, bigint, string], string>,
  /**
   * / Create a world. Admin only.
   */
  'createWorld' : ActorMethod<[World], string>,
  /**
   * / Delete a lesson. Admin only.
   */
  'deleteLesson' : ActorMethod<[string], undefined>,
  /**
   * / Delete a quest. Admin only.
   */
  'deleteQuest' : ActorMethod<[string], undefined>,
  /**
   * / Delete a skill node. Admin only.
   */
  'deleteSkillNode' : ActorMethod<[string], undefined>,
  /**
   * / Delete a user record. Only the owning principal or an admin may delete it.
   */
  'deleteUser' : ActorMethod<[string], undefined>,
  /**
   * / Delete a world. Admin only.
   */
  'deleteWorld' : ActorMethod<[string], undefined>,
  /**
   * / Get the caller's own profile.
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Get daily quests for a user. Only the owning user or an admin may call this.
   */
  'getDailyQuests' : ActorMethod<[string], Array<Quest>>,
  /**
   * / Read a lesson. Any authenticated user may read lesson data.
   */
  'getLesson' : ActorMethod<[string], [] | [Lesson]>,
  /**
   * / List lessons for a specific world. Any authenticated user may call this.
   */
  'getLessonsByWorld' : ActorMethod<[string], Array<Lesson>>,
  /**
   * / Get a multiplayer session. Participants or admins only.
   */
  'getMultiplayerSession' : ActorMethod<[string], [] | [MultiplayerSession]>,
  /**
   * / Read a quest. Any authenticated user may read quest data.
   */
  'getQuest' : ActorMethod<[string], [] | [Quest]>,
  /**
   * / Read a skill node. Any authenticated user may read skill node data.
   */
  'getSkillNode' : ActorMethod<[string], [] | [SkillNode]>,
  /**
   * / Get all skill nodes for a subject. Any authenticated user may call this.
   */
  'getSkillTree' : ActorMethod<[Subject], Array<SkillNode>>,
  /**
   * / Get streak status for a user. Only the owning user or an admin may call this.
   */
  'getStreakStatus' : ActorMethod<[string], [] | [StreakRecord]>,
  /**
   * / Get a tutor recommendation for a user. Only the owning user or an admin may call this.
   */
  'getTutorRecommendation' : ActorMethod<
    [string, Subject],
    TutorRecommendation
  >,
  /**
   * / Retrieve a user record. Only the owning principal or an admin may read it.
   */
  'getUser' : ActorMethod<[string], [] | [User]>,
  /**
   * / Fetch another user's profile. Callers may only view their own profile
   * / unless they are an admin.
   */
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  /**
   * / Get all purchases for a user. Only the owning user or an admin may call this.
   */
  'getUserPurchases' : ActorMethod<[string], Array<Purchase>>,
  /**
   * / Get all skill nodes unlocked by a user. Only the owning user or an admin may call this.
   */
  'getUserSkillNodes' : ActorMethod<[string], Array<UserSkillNode>>,
  /**
   * / Read a world. Any authenticated user may read world data.
   */
  'getWorld' : ActorMethod<[string], [] | [World]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Join a multiplayer challenge. Only authenticated users may join challenges.
   */
  'joinChallenge' : ActorMethod<[string, string], undefined>,
  /**
   * / List all lessons. Any authenticated user may list lessons.
   */
  'listLessons' : ActorMethod<[], Array<Lesson>>,
  /**
   * / List all worlds. Any authenticated user may list worlds.
   */
  'listWorlds' : ActorMethod<[], Array<World>>,
  /**
   * / Purchase an item from the shop. Only the owning user may make purchases.
   */
  'purchaseItem' : ActorMethod<[string, PurchaseType, string], string>,
  /**
   * / Record a lesson result for a user. Only the owning user may record their results.
   */
  'recordLessonResult' : ActorMethod<[string, string, bigint], undefined>,
  /**
   * / Record a daily login for a user. Only the owning user may record their login.
   */
  'recordLogin' : ActorMethod<[string], undefined>,
  /**
   * / Resolve a multiplayer session. Only authenticated users (participants) or admins may resolve.
   */
  'resolveSession' : ActorMethod<[string], undefined>,
  /**
   * / Save / update the caller's own profile.
   */
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Submit answers for a multiplayer session. Only the participating user may submit.
   */
  'submitAnswers' : ActorMethod<[string, string, Array<Answer>], undefined>,
  /**
   * / Unlock a skill node for a user. Only the owning user may unlock their nodes.
   */
  'unlockSkillNode' : ActorMethod<[string, string], undefined>,
  /**
   * / Update a lesson. Admin only.
   */
  'updateLesson' : ActorMethod<[Lesson], undefined>,
  /**
   * / Update a quest. Admin only.
   */
  'updateQuest' : ActorMethod<[Quest], undefined>,
  /**
   * / Update a skill node. Admin only.
   */
  'updateSkillNode' : ActorMethod<[SkillNode], undefined>,
  /**
   * / Update a user record. Only the owning principal or an admin may update it.
   */
  'updateUser' : ActorMethod<[User], undefined>,
  /**
   * / Update a world. Admin only.
   */
  'updateWorld' : ActorMethod<[World], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];