/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Subject = IDL.Variant({ 'math' : IDL.Null, 'english' : IDL.Null });
export const Difficulty = IDL.Variant({
  'mastery' : IDL.Null,
  'intermediate' : IDL.Null,
  'elementary' : IDL.Null,
  'beginner' : IDL.Null,
  'advanced' : IDL.Null,
  'expert' : IDL.Null,
});
export const Lesson = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'subject' : Subject,
  'xpReward' : IDL.Nat,
  'difficulty' : Difficulty,
  'coinReward' : IDL.Nat,
  'worldId' : IDL.Text,
  'isBossBattle' : IDL.Bool,
});
export const Quest = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'expiresAt' : IDL.Int,
  'xpReward' : IDL.Nat,
  'description' : IDL.Text,
  'coinReward' : IDL.Nat,
  'isDaily' : IDL.Bool,
});
export const SkillNode = IDL.Record({
  'id' : IDL.Text,
  'subject' : Subject,
  'requiredLevel' : IDL.Nat,
  'name' : IDL.Text,
  'prerequisiteIds' : IDL.Vec(IDL.Text),
});
export const World = IDL.Record({
  'id' : IDL.Text,
  'subject' : Subject,
  'requiredLevel' : IDL.Nat,
  'difficulty' : Difficulty,
  'name' : IDL.Text,
  'isUnlocked' : IDL.Bool,
  'bossDefeated' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'username' : IDL.Text,
  'avatarId' : IDL.Text,
});
export const SessionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const MultiplayerSession = IDL.Record({
  'id' : IDL.Text,
  'status' : SessionStatus,
  'opponentId' : IDL.Opt(IDL.Text),
  'subject' : Subject,
  'winnerId' : IDL.Opt(IDL.Text),
  'hostId' : IDL.Text,
});
export const StreakRecord = IDL.Record({
  'userId' : IDL.Text,
  'longestStreak' : IDL.Nat,
  'lastStreakDate' : IDL.Int,
  'currentStreak' : IDL.Nat,
});
export const TutorRecommendation = IDL.Record({
  'recommendedLesson' : IDL.Text,
  'hint' : IDL.Text,
  'difficultyAdjustment' : Difficulty,
});
export const User = IDL.Record({
  'id' : IDL.Text,
  'xp' : IDL.Nat,
  'age' : IDL.Nat,
  'lastLoginDate' : IDL.Int,
  'principal' : IDL.Principal,
  'username' : IDL.Text,
  'gems' : IDL.Nat,
  'coins' : IDL.Nat,
  'streakDays' : IDL.Nat,
  'level' : IDL.Nat,
  'avatarId' : IDL.Text,
  'currentWorldId' : IDL.Text,
  'subjectProgress' : IDL.Vec(IDL.Tuple(Subject, IDL.Nat)),
});
export const PurchaseType = IDL.Variant({
  'hintPack' : IDL.Null,
  'worldSkin' : IDL.Null,
  'avatarCostume' : IDL.Null,
});
export const Purchase = IDL.Record({
  'id' : IDL.Text,
  'itemId' : IDL.Text,
  'purchaseDate' : IDL.Int,
  'cost' : IDL.Nat,
  'userId' : IDL.Text,
  'itemType' : PurchaseType,
});
export const UserSkillNode = IDL.Record({
  'userId' : IDL.Text,
  'unlocked' : IDL.Bool,
  'skillNodeId' : IDL.Text,
});
export const Answer = IDL.Record({
  'isCorrect' : IDL.Bool,
  'questionId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimStreakReward' : IDL.Func([IDL.Text], [IDL.Text], []),
  'completeQuest' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createChallenge' : IDL.Func([IDL.Text, Subject], [IDL.Text], []),
  'createLesson' : IDL.Func([Lesson], [IDL.Text], []),
  'createQuest' : IDL.Func([Quest], [IDL.Text], []),
  'createSkillNode' : IDL.Func([SkillNode], [IDL.Text], []),
  'createUser' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Text], []),
  'createWorld' : IDL.Func([World], [IDL.Text], []),
  'deleteLesson' : IDL.Func([IDL.Text], [], []),
  'deleteQuest' : IDL.Func([IDL.Text], [], []),
  'deleteSkillNode' : IDL.Func([IDL.Text], [], []),
  'deleteUser' : IDL.Func([IDL.Text], [], []),
  'deleteWorld' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyQuests' : IDL.Func([IDL.Text], [IDL.Vec(Quest)], ['query']),
  'getLesson' : IDL.Func([IDL.Text], [IDL.Opt(Lesson)], ['query']),
  'getLessonsByWorld' : IDL.Func([IDL.Text], [IDL.Vec(Lesson)], ['query']),
  'getMultiplayerSession' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(MultiplayerSession)],
      ['query'],
    ),
  'getQuest' : IDL.Func([IDL.Text], [IDL.Opt(Quest)], ['query']),
  'getSkillNode' : IDL.Func([IDL.Text], [IDL.Opt(SkillNode)], ['query']),
  'getSkillTree' : IDL.Func([Subject], [IDL.Vec(SkillNode)], ['query']),
  'getStreakStatus' : IDL.Func([IDL.Text], [IDL.Opt(StreakRecord)], ['query']),
  'getTutorRecommendation' : IDL.Func(
      [IDL.Text, Subject],
      [TutorRecommendation],
      ['query'],
    ),
  'getUser' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserPurchases' : IDL.Func([IDL.Text], [IDL.Vec(Purchase)], ['query']),
  'getUserSkillNodes' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(UserSkillNode)],
      ['query'],
    ),
  'getWorld' : IDL.Func([IDL.Text], [IDL.Opt(World)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinChallenge' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'listLessons' : IDL.Func([], [IDL.Vec(Lesson)], ['query']),
  'listWorlds' : IDL.Func([], [IDL.Vec(World)], ['query']),
  'purchaseItem' : IDL.Func([IDL.Text, PurchaseType, IDL.Text], [IDL.Text], []),
  'recordLessonResult' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'recordLogin' : IDL.Func([IDL.Text], [], []),
  'resolveSession' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitAnswers' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(Answer)], [], []),
  'unlockSkillNode' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateLesson' : IDL.Func([Lesson], [], []),
  'updateQuest' : IDL.Func([Quest], [], []),
  'updateSkillNode' : IDL.Func([SkillNode], [], []),
  'updateUser' : IDL.Func([User], [], []),
  'updateWorld' : IDL.Func([World], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Subject = IDL.Variant({ 'math' : IDL.Null, 'english' : IDL.Null });
  const Difficulty = IDL.Variant({
    'mastery' : IDL.Null,
    'intermediate' : IDL.Null,
    'elementary' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
    'expert' : IDL.Null,
  });
  const Lesson = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'subject' : Subject,
    'xpReward' : IDL.Nat,
    'difficulty' : Difficulty,
    'coinReward' : IDL.Nat,
    'worldId' : IDL.Text,
    'isBossBattle' : IDL.Bool,
  });
  const Quest = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'expiresAt' : IDL.Int,
    'xpReward' : IDL.Nat,
    'description' : IDL.Text,
    'coinReward' : IDL.Nat,
    'isDaily' : IDL.Bool,
  });
  const SkillNode = IDL.Record({
    'id' : IDL.Text,
    'subject' : Subject,
    'requiredLevel' : IDL.Nat,
    'name' : IDL.Text,
    'prerequisiteIds' : IDL.Vec(IDL.Text),
  });
  const World = IDL.Record({
    'id' : IDL.Text,
    'subject' : Subject,
    'requiredLevel' : IDL.Nat,
    'difficulty' : Difficulty,
    'name' : IDL.Text,
    'isUnlocked' : IDL.Bool,
    'bossDefeated' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'username' : IDL.Text,
    'avatarId' : IDL.Text,
  });
  const SessionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const MultiplayerSession = IDL.Record({
    'id' : IDL.Text,
    'status' : SessionStatus,
    'opponentId' : IDL.Opt(IDL.Text),
    'subject' : Subject,
    'winnerId' : IDL.Opt(IDL.Text),
    'hostId' : IDL.Text,
  });
  const StreakRecord = IDL.Record({
    'userId' : IDL.Text,
    'longestStreak' : IDL.Nat,
    'lastStreakDate' : IDL.Int,
    'currentStreak' : IDL.Nat,
  });
  const TutorRecommendation = IDL.Record({
    'recommendedLesson' : IDL.Text,
    'hint' : IDL.Text,
    'difficultyAdjustment' : Difficulty,
  });
  const User = IDL.Record({
    'id' : IDL.Text,
    'xp' : IDL.Nat,
    'age' : IDL.Nat,
    'lastLoginDate' : IDL.Int,
    'principal' : IDL.Principal,
    'username' : IDL.Text,
    'gems' : IDL.Nat,
    'coins' : IDL.Nat,
    'streakDays' : IDL.Nat,
    'level' : IDL.Nat,
    'avatarId' : IDL.Text,
    'currentWorldId' : IDL.Text,
    'subjectProgress' : IDL.Vec(IDL.Tuple(Subject, IDL.Nat)),
  });
  const PurchaseType = IDL.Variant({
    'hintPack' : IDL.Null,
    'worldSkin' : IDL.Null,
    'avatarCostume' : IDL.Null,
  });
  const Purchase = IDL.Record({
    'id' : IDL.Text,
    'itemId' : IDL.Text,
    'purchaseDate' : IDL.Int,
    'cost' : IDL.Nat,
    'userId' : IDL.Text,
    'itemType' : PurchaseType,
  });
  const UserSkillNode = IDL.Record({
    'userId' : IDL.Text,
    'unlocked' : IDL.Bool,
    'skillNodeId' : IDL.Text,
  });
  const Answer = IDL.Record({
    'isCorrect' : IDL.Bool,
    'questionId' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimStreakReward' : IDL.Func([IDL.Text], [IDL.Text], []),
    'completeQuest' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createChallenge' : IDL.Func([IDL.Text, Subject], [IDL.Text], []),
    'createLesson' : IDL.Func([Lesson], [IDL.Text], []),
    'createQuest' : IDL.Func([Quest], [IDL.Text], []),
    'createSkillNode' : IDL.Func([SkillNode], [IDL.Text], []),
    'createUser' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Text], []),
    'createWorld' : IDL.Func([World], [IDL.Text], []),
    'deleteLesson' : IDL.Func([IDL.Text], [], []),
    'deleteQuest' : IDL.Func([IDL.Text], [], []),
    'deleteSkillNode' : IDL.Func([IDL.Text], [], []),
    'deleteUser' : IDL.Func([IDL.Text], [], []),
    'deleteWorld' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyQuests' : IDL.Func([IDL.Text], [IDL.Vec(Quest)], ['query']),
    'getLesson' : IDL.Func([IDL.Text], [IDL.Opt(Lesson)], ['query']),
    'getLessonsByWorld' : IDL.Func([IDL.Text], [IDL.Vec(Lesson)], ['query']),
    'getMultiplayerSession' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(MultiplayerSession)],
        ['query'],
      ),
    'getQuest' : IDL.Func([IDL.Text], [IDL.Opt(Quest)], ['query']),
    'getSkillNode' : IDL.Func([IDL.Text], [IDL.Opt(SkillNode)], ['query']),
    'getSkillTree' : IDL.Func([Subject], [IDL.Vec(SkillNode)], ['query']),
    'getStreakStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(StreakRecord)],
        ['query'],
      ),
    'getTutorRecommendation' : IDL.Func(
        [IDL.Text, Subject],
        [TutorRecommendation],
        ['query'],
      ),
    'getUser' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserPurchases' : IDL.Func([IDL.Text], [IDL.Vec(Purchase)], ['query']),
    'getUserSkillNodes' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UserSkillNode)],
        ['query'],
      ),
    'getWorld' : IDL.Func([IDL.Text], [IDL.Opt(World)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinChallenge' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'listLessons' : IDL.Func([], [IDL.Vec(Lesson)], ['query']),
    'listWorlds' : IDL.Func([], [IDL.Vec(World)], ['query']),
    'purchaseItem' : IDL.Func(
        [IDL.Text, PurchaseType, IDL.Text],
        [IDL.Text],
        [],
      ),
    'recordLessonResult' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'recordLogin' : IDL.Func([IDL.Text], [], []),
    'resolveSession' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitAnswers' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(Answer)], [], []),
    'unlockSkillNode' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateLesson' : IDL.Func([Lesson], [], []),
    'updateQuest' : IDL.Func([Quest], [], []),
    'updateSkillNode' : IDL.Func([SkillNode], [], []),
    'updateUser' : IDL.Func([User], [], []),
    'updateWorld' : IDL.Func([World], [], []),
  });
};

export const init = ({ IDL }) => { return []; };